# Generated by Django 4.1.7 on 2023-03-08 05:36

import academyapi.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[academyapi.validators.validate_letters_only])),
                ('last_name', models.CharField(max_length=20, validators=[academyapi.validators.validate_letters_only])),
                ('identification', models.CharField(max_length=10)),
                ('age', models.SmallIntegerField(validators=[academyapi.validators.validate_age])),
            ],
        ),
        migrations.CreateModel(
            name='Grimoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('leaves', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MagicAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Rejected'), ('3', 'Accepted')], default='1', max_length=1)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academyapi.applicant')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='grimoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academyapi.grimoire'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='magic_affinity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academyapi.magicaffinity'),
        ),
    ]
